server:
  port: 8081

spring:
  application:
    name: analytics-service

  data:
    mongodb:
      uri: mongodb://mongo:mongo123@localhost:27017/analytics_db?authSource=admin

  # Configuração do Consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: adminpassword